// 📦 Liste complète du matériel (importée par /api/instruments/seed)
export const items = [
    { "name": "Canon 60D",  "categorie": "Appareils photo", "quantite": 4 },
    { "name": "Canon 700D", "categorie": "Appareils photo", "quantite": 3 },
    { "name": "Canon 850D", "categorie": "Appareils photo", "quantite": 8 },
    { "name": "Sony ZV-1",  "categorie": "Appareils photo", "quantite": 2 },
    { "name": "Canon 350D", "categorie": "Appareils photo", "quantite": 2 },
    { "name": "Canon 400D", "categorie": "Appareils photo", "quantite": 3 },
    { "name": "Canon 50D",  "categorie": "Appareils photo", "quantite": 1 },
    { "name": "Canon 40D",  "categorie": "Appareils photo", "quantite": 1 },
    { "name": "Kit Vlogger Rode (téléphone)", "categorie": "Appareils photo", "quantite": 1 },

    { "name": "Objectif Canon 28-80mm f/3.5-5.6", "categorie": "Objectifs (photo)", "quantite": 2 },
    { "name": "Objectif Canon 28-90mm",          "categorie": "Objectifs (photo)", "quantite": 2 },
    { "name": "Objectif Canon 18-55mm",          "categorie": "Objectifs (photo)", "quantite": 2 },
    { "name": "Objectif Canon 18-135mm f/3.5-5.6","categorie": "Objectifs (photo)", "quantite": 10 },
    { "name": "Objectif Canon 18-200mm f/3.5-5.6 IS","categorie": "Objectifs (photo)", "quantite": 1 },
    { "name": "Objectif Sigma 17-50mm f/2.8",    "categorie": "Objectifs (photo)", "quantite": 3 },
    { "name": "Objectif Sigma 17-70mm f/2.8-4",  "categorie": "Objectifs (photo)", "quantite": 1 },
    { "name": "Objectif Canon 50mm f/1.4",       "categorie": "Objectifs (photo)", "quantite": 1 },
    { "name": "Objectif 50mm f/1.8",             "categorie": "Objectifs (photo)", "quantite": 1 },
    { "name": "Objectif 60mm f/2.8 Macro",       "categorie": "Objectifs (photo)", "quantite": 1 },
    { "name": "Objectif Canon 75-300mm f/4-5.6 III USM","categorie": "Objectifs (photo)", "quantite": 1 },
    { "name": "Objectif 35mm",                   "categorie": "Objectifs (photo)", "quantite": 1 },
    { "name": "Objectif Sigma 70-200mm f/2.8 Macro II HSM","categorie": "Objectifs (photo)", "quantite": 1 },
    { "name": "Objectif Sigma 20mm f/1.8",       "categorie": "Objectifs (photo)", "quantite": 1 },
    { "name": "Objectif Canon 85mm f/1.8",       "categorie": "Objectifs (photo)", "quantite": 1 },

    { "name": "Objectif Samyang 35mm T1.5 (Canon)", "categorie": "Objectifs (vidéo)", "quantite": 2 },
    { "name": "Objectif Samyang 24mm T1.5 (Canon)", "categorie": "Objectifs (vidéo)", "quantite": 2 },
    { "name": "Objectif Sigma 18-35mm f/1.8 DC HSM (Canon)", "categorie": "Objectifs (vidéo)", "quantite": 2 },
    { "name": "Objectif Sigma 50-100mm f/1.8 DC HSM (Canon)", "categorie": "Objectifs (vidéo)", "quantite": 1 },

    { "name": "Wacom Intuos Pro PTH-660", "categorie": "Graphisme", "quantite": 15 },
    { "name": "Wacom Intuos PTZ-930",     "categorie": "Graphisme", "quantite": 9 },
    { "name": "Stylet Wacom ZP-501E",     "categorie": "Graphisme", "quantite": 20 },
    { "name": "Souris 3Dconnexion",       "categorie": "Graphisme", "quantite": 15 },

    { "name": "Trépied photo Manfrotto TR190XPROB + rotule HD804RC2", "categorie": "Trépieds / Stabilisateurs", "quantite": 4 },
    { "name": "Trépied vidéo Manfrotto MT290XTA3 + rotule 128RC",     "categorie": "Trépieds / Stabilisateurs", "quantite": 4 },
    { "name": "Trépied vidéo Manfrotto 055A + rotule 700RC2",         "categorie": "Trépieds / Stabilisateurs", "quantite": 8 },
    { "name": "Monopode Benro A38FD",                                 "categorie": "Trépieds / Stabilisateurs", "quantite": 4 },
    { "name": "Trépied caméra Vinter Pro130",                         "categorie": "Trépieds / Stabilisateurs", "quantite": 1 },
    { "name": "Trépied caméra Manfrotto 501",                         "categorie": "Trépieds / Stabilisateurs", "quantite": 1 },
    { "name": "Dolly Manfrotto 181B",                                 "categorie": "Trépieds / Stabilisateurs", "quantite": 2 },
    { "name": "Stabilisateur mécanique Manfrotto (avec adaptateur rapide)", "categorie": "Trépieds / Stabilisateurs", "quantite": 1 },
    { "name": "Stabilisateur DJI Osmo Mobile (smartphone)",           "categorie": "Trépieds / Stabilisateurs", "quantite": 10 },
    { "name": "Mini-trépieds",                                        "categorie": "Trépieds / Stabilisateurs", "quantite": 7 },
    { "name": "Stabilisateur DJI Ronin SC2 Pro Combo (APN)",          "categorie": "Trépieds / Stabilisateurs", "quantite": 2 },

    { "name": "Kit 2 éclairages DÖRR DLP-100W (avec batteries)", "categorie": "Éclairage", "quantite": 2 },
    { "name": "Projecteur Bambino 500W (secteur)",                 "categorie": "Éclairage", "quantite": 3 },
    { "name": "Réflecteur",                                       "categorie": "Éclairage", "quantite": 11 },
    { "name": "Trépieds & supports pour réflecteurs",             "categorie": "Éclairage", "quantite": 6 },
    { "name": "Packshot mini-studio SP40",                        "categorie": "Éclairage", "quantite": 5 },
    { "name": "Flash Cobra Speedlite 430EX",                      "categorie": "Éclairage", "quantite": 1 },

    { "name": "Enregistreur Zoom H5",                       "categorie": "Audio", "quantite": 3 },
    { "name": "Micro Rode VideoMic (APN / caméscope)",      "categorie": "Audio", "quantite": 6 },
    { "name": "Micro Rode NT-USB Mini (PC)",                "categorie": "Audio", "quantite": 1 },
    { "name": "Micro-cravate Azden ProX-ReR (ITW)",         "categorie": "Audio", "quantite": 4 },
    { "name": "Micro Sennheiser K6-ME64 (perche, distance)","categorie": "Audio", "quantite": 2 },
    { "name": "Micro Sennheiser E835 (proxi)",              "categorie": "Audio", "quantite": 2 },
    { "name": "Micro Sennheiser MD46 (proxi)",              "categorie": "Audio", "quantite": 3 },
    { "name": "Micro Sennheiser E815S (proxi)",             "categorie": "Audio", "quantite": 1 },
    { "name": "Bras micro + filtre pop-up Speedlink Volity","categorie": "Audio", "quantite": 1 },
    { "name": "Câble XLR-Jack double mono",                 "categorie": "Audio", "quantite": 6 },
    { "name": "Câble XLR-Jack stéréo 3m",                   "categorie": "Audio", "quantite": 5 },
    { "name": "Casque Sennheiser EH150",                    "categorie": "Audio", "quantite": 14 },
    { "name": "Contrôleur NanoKONTROL 2 (Korg)",            "categorie": "Audio", "quantite": 16 },
    { "name": "Contrôleur Ableton Push 2",                  "categorie": "Audio", "quantite": 2 },

    { "name": "Blackmagic DaVinci Resolve Micro Panel",     "categorie": "Étalonnage", "quantite": 2 }
]


